// Product actions
export const LOADING = 'LOADING';
export const ERROR = 'MAKE_REQUEST';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

// Order actions
export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const GET_ORDER_LOADING = 'GET_ORDER_LOADING';
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR';
export const GET_USER_ORDERS_LOADING = 'GET_USER_ORDERS_LOADING';
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const GET_USER_ORDERS_ERROR = 'GET_USER_ORDERS_ERROR';
export const CREATE_ORDER_LOADING = 'CREATE_ORDER_LOADING';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const GET_TERMINALS_LOADING = 'GET_TERMINALS_LOADING';
export const GET_TERMINALS = 'GET_TERMINALS';
export const GET_TERMINALS_ERROR = 'GET_TERMINALS_ERROR';
export const ORDER_IS_SEEN_ACTION_LOADING = 'ORDER_IS_SEEN_ACTION_LOADING';
export const ORDER_IS_SEEN_ACTION = 'ORDER_IS_SEEN_ACTION';
export const ORDER_IS_SEEN_ACTION_ERROR = 'ORDER_IS_SEEN_ACTION_ERROR';
export const CHANGE_ORDER_STATUS_LOADING = 'CHANGE_ORDER_STATUS_LOADING';
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
export const CHANGE_ORDER_STATUS_ERROR = 'CHANGE_ORDER_STATUS_ERROR';

// Auth actions
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const VALIDATE_LOADING = 'VALIDATE_LOADING';
export const LOG_IN_LOADING = 'LOG_IN_LOADING';
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const LOG_IN = 'LOG_IN';
export const GET_USER = 'GET_USER';
export const VALIDATE_USER = 'VALIDATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const DELETE_ACCOUNT_LOADING = 'DELETE_ACCOUNT_LOADING';
export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR';

// Wishlist actions
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

// Cart actions
export const ADD_CART = 'ADD_CART';
export const ADD_CART_ONE = 'ADD_CART_ONE';
export const REMOVE_CART = 'REMOVE_CART';
export const CLEAR_CART = 'CLEAR_CART';

// Menu actions
export const SHOW_SHOP = 'SHOW_SHOP';
export const SHOW_FABRIC = 'SHOW_FABRIC';
export const SHOW_JOURNAL = 'SHOW_JOURNAL';
export const SHOW_ABOUT = 'SHOW_ABOUT';

// Sort actions
export const SORT_OLDEST = 'SORT_OLDEST';
export const SORT_NEWEST = 'SORT_NEWEST';
export const SORT_CHEAPEST = 'SORT_CHEAPEST';
export const SORT_EXPENSIVEST = 'SORT_EXPENSIVEST';
export const SORT_NAME = 'SORT_NAME';
export const SORT_DISCOUNT = 'SORT_DISCOUNT';

// Filter actions
export const SET_FILTER_APPARELTERM = 'FILTER_APPARELS';
export const SET_FILTER_BRANDTERM = 'FILTER_BRANDS';
export const RESET_FILTERS = 'RESET_FILTERS';
