export const LOADING = 'LOADING';
export const ERROR = 'MAKE_REQUEST';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const VALIDATE_LOADING = 'VALIDATE_LOADING';
export const LOG_IN_LOADING = 'LOG_IN_LOADING';
export const LOG_IN = 'LOG_IN';
export const VALIDATE_USER = 'VALIDATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const SHOW_SHOP = 'SHOW_SHOP';
export const SHOW_FABRIC = 'SHOW_FABRIC';
export const SHOW_JOURNAL = 'SHOW_JOURNAL';
export const SHOW_ABOUT = 'SHOW_ABOUT';

export const SORT_OLDEST = 'SORT_OLDEST';
export const SORT_NEWEST = 'SORT_NEWEST';
export const SORT_CHEAPEST = 'SORT_CHEAPEST';
export const SORT_EXPENSIVEST = 'SORT_EXPENSIVEST';
export const SORT_NAME = 'SORT_NAME';
export const SORT_DISCOUNT = 'SORT_DISCOUNT';

export const SET_FILTER_APPARELTERM = 'FILTER_APPARELS';
export const SET_FILTER_BRANDTERM = 'FILTER_BRANDS';
export const RESET_FILTERS = 'RESET_FILTERS';
